import { $, $$, fetchJson, state, showChartLoading, hideChartLoading, destroyChart, formatMoney, formatPct } from './common.js';

// Zoomable options helper
export function _zoomableLineOptions({ yLabel, yCallback, stacked, legendPos } = {}) {
  return {
    responsive: true, maintainAspectRatio: false,
    interaction: { intersect: false, mode: 'index' },
    scales: {
      y: { stacked: stacked || false, ticks: { color: '#8ea0b8', callback: yCallback || (v => v) }, title: { display: true, text: yLabel || '', color: '#8ea0b8' } },
      x: { ticks: { color: '#8ea0b8', maxTicksLimit: 12 } },
    },
    plugins: {
      legend: { position: legendPos || 'top', labels: { color: '#d9e2f2', usePointStyle: true, padding: 8, font: { size: 11 } } },
      zoom: {
        zoom: { wheel: { enabled: true, modifierKey: 'ctrl' }, pinch: { enabled: true }, drag: { enabled: true, backgroundColor: 'rgba(88,166,255,0.1)', borderColor: '#58a6ff', borderWidth: 1 }, mode: 'x' },
        pan: { enabled: true, mode: 'x', modifierKey: 'ctrl' },
      },
    },
  };
}

export function _destroyAndClear(key) { if (state.charts[key]) { state.charts[key].destroy(); state.charts[key] = null; } }

let _returnsByCompanyData = null;
let _mwReturnsData = null;
let _contribData = null;
let _divGrowthMode = 'agg';

export function renderChartsTab() { refreshAllCharts(); }

export function renderValueChart() {
  const breakdown = $('#pf-value-breakdown')?.checked;
  if (breakdown) { renderValueBreakdown(); return; }
  const ccy = state.chartSettings.currency;
  showChartLoading('pf-value-chart');
  fetchJson('/api/portfolio/holdings/history?base_currency=' + ccy).then(daily => {
    if (!daily.length) { hideChartLoading('pf-value-chart'); return; }
    state.chartRawData.value = daily;
    const ctx = $('#pf-value-chart'); destroyChart('value'); hideChartLoading('pf-value-chart');
    state.charts.value = new Chart(ctx, { type: 'line', data: { labels: daily.map(d => d.date), datasets: [{ label: 'Total Value (' + ccy + ')', data: daily.map(d => d.total_value), borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.1)', fill: true, tension: 0.2, pointRadius: 0 }, { label: 'Cash (' + ccy + ')', data: daily.map(d => d.cash_balance), borderColor: '#44d17b', borderDash: [5, 3], tension: 0.2, pointRadius: 0 }], }, options: _zoomableLineOptions({ yLabel: ccy, yCallback: v => formatMoney(v), }), });
  });
}

const _VALUE_COLORS = ['#58a6ff','#44d17b','#e0af4f','#ff6b6b','#8ea0b8','#58a6ffcc','#44d17bcc','#e0af4fcc','#ff6b6bcc','#8ea0b8cc','#58a6ff88','#44d17b88','#e0af4f88','#ff6b6b88','#8ea0b888'];

export function renderValueBreakdown() {
  const ccy = state.chartSettings.currency; showChartLoading('pf-value-chart'); Promise.all([ fetchJson('/api/portfolio/holdings/history/constituents?base_currency=' + ccy), fetchJson('/api/portfolio/holdings/history?base_currency=' + ccy), ]).then(([constituents, daily]) => {
    const ctx = $('#pf-value-chart'); if (!constituents || !constituents.dates || !constituents.dates.length || !daily.length) { hideChartLoading('pf-value-chart'); return; }
    destroyChart('value');
    const syms = Object.keys(constituents.series).sort((a, b) => { const sumA = (constituents.series[a] || []).reduce((s, v) => s + (v || 0), 0); const sumB = (constituents.series[b] || []).reduce((s, v) => s + (v || 0), 0); return sumA - sumB; });
    const cashMap = {}; for (const d of daily) cashMap[d.date] = d.cash_balance || 0; const datasets = []; for (let i = 0; i < syms.length; i++) { const sym = syms[i]; const vals = constituents.series[sym] || []; datasets.push({ label: sym, data: vals, backgroundColor: _VALUE_COLORS[i % _VALUE_COLORS.length], fill: true, tension: 0.2, pointRadius: 0, borderWidth: 0, spanGaps: false, }); }
    datasets.push({ label: 'Cash', data: constituents.dates.map(d => cashMap[d] || null), borderColor: '#44d17b', borderDash: [5, 3], tension: 0.2, pointRadius: 0, fill: false, borderWidth: 2, });
    hideChartLoading('pf-value-chart'); state.charts.value = new Chart(ctx, { type: 'line', data: { labels: constituents.dates, datasets, }, options: _zoomableLineOptions({ yLabel: ccy, yCallback: v => formatMoney(v), stacked: true, legendPos: 'right' }), });
  });
}

export function renderDividendsChart() {
  const period = $('#pf-div-period')?.value || 'monthly'; const ccy = state.chartSettings.currency; showChartLoading('pf-dividends-chart'); fetchJson(`/api/portfolio/dividends/history?period=${period}&base_currency=${ccy}`).then(data => { if (!data || !data.length) { hideChartLoading('pf-dividends-chart'); return; } state.chartRawData.dividends = data; const ctx = $('#pf-dividends-chart'); destroyChart('dividends'); hideChartLoading('pf-dividends-chart'); state.charts.dividends = new Chart(ctx, { type: 'bar', data: { labels: data.map(d => d.period), datasets: [{ label: 'Gross', data: data.map(d => d.gross), backgroundColor: 'rgba(68,209,123,0.6)', borderColor: '#44d17b', borderWidth: 1, borderRadius: 2, }, { label: 'Tax', data: data.map(d => -d.tax), backgroundColor: 'rgba(255,107,107,0.5)', borderColor: '#ff6b6b', borderWidth: 1, borderRadius: 2, }, { label: 'Net', data: data.map(d => d.net), type: 'line', borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.15)', borderWidth: 2.5, tension: 0.2, pointRadius: 3, pointBackgroundColor: '#58a6ff', fill: false, }, ], }, options: { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { y: { ticks: { color: '#8ea0b8', callback: v => formatMoney(v) }, title: { display: true, text: ccy, color: '#8ea0b8' } }, x: { ticks: { color: '#8ea0b8', maxTicksLimit: 12 } }, }, plugins: { legend: { labels: { color: '#d9e2f2', usePointStyle: true } }, tooltip: { callbacks: { label: ctx => `${ctx.dataset.label}: ${formatMoney(ctx.raw)}` } }, }, }, }); });
}

export function renderAllocationChart() {
  const hh = state.holdings.filter(h => !h.is_option);
  if (!hh.length) return; state.chartRawData.allocation = { labels: hh.map(h => h.symbol), values: hh.map(h => Math.abs(h.market_value || 0)) }; const ctx = $('#pf-allocation-chart'); destroyChart('allocation'); const labels = hh.map(h => h.symbol); const data = hh.map(h => Math.abs(h.market_value || 0)); hideChartLoading('pf-allocation-chart'); state.charts.allocation = new Chart(ctx, { type: 'doughnut', data: { labels, datasets: [{ data, backgroundColor: ['#58a6ff','#44d17b','#e0af4f','#ff6b6b','#8ea0b8','#58a6ff88','#44d17b88','#e0af4f88','#ff6b6b88','#8ea0b888'], borderColor: 'transparent', }], }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'right', labels: { color: '#d9e2f2', usePointStyle: true, padding: 12 } }, tooltip: { callbacks: { label: ctx => `${ctx.label}: ${formatMoney(ctx.raw)}` } }, }, }, });
}

export function renderDividendGrowthChart() {
  const ccy = state.chartSettings.currency; showChartLoading('pf-div-growth-chart'); fetchJson('/api/portfolio/dividends/yoy?base_currency=' + ccy).then(data => { if (!data || !data.years || !data.years.length) { hideChartLoading('pf-div-growth-chart'); return; } state.chartRawData.divGrowth = data; const ctx = $('#pf-div-growth-chart'); destroyChart('divGrowth'); hideChartLoading('pf-div-growth-chart'); state.charts.divGrowth = new Chart(ctx, { type: 'bar', data: { labels: data.years.map(y => String(y)), datasets: [{ label: 'Dividends (' + (data.currency || 'EUR') + ')', data: data.dividends, backgroundColor: 'rgba(68,209,123,0.55)', borderColor: '#44d17b', borderWidth: 1, borderRadius: 2, order: 2, }, { label: 'YoY Growth %', data: data.yoy_growth, type: 'line', borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.1)', borderWidth: 2.5, tension: 0.2, pointRadius: 4, pointBackgroundColor: '#58a6ff', yAxisID: 'y1', order: 1, }, ], }, options: { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { y: { position: 'left', ticks: { color: '#8ea0b8', callback: v => formatMoney(v) }, title: { display: true, text: data.currency || 'EUR', color: '#8ea0b8' }, }, y1: { position: 'right', ticks: { color: '#58a6ff', callback: v => v.toFixed(1) + '%' }, grid: { drawOnChartArea: false }, }, x: { ticks: { color: '#8ea0b8' } }, }, plugins: { legend: { labels: { color: '#d9e2f2', usePointStyle: true } }, tooltip: { callbacks: { label: (ctx) => { if (ctx.dataset.label === 'YoY Growth %') { return 'YoY Growth: ' + (ctx.raw != null ? ctx.raw.toFixed(1) + '%' : 'N/A'); } return 'Dividends: ' + formatMoney(ctx.raw); }, }, }, }, }, }); });
}

export function renderDpsPerCompanyChart() {
  showChartLoading('pf-div-growth-chart'); fetchJson('/api/portfolio/dividends/yoy/per-company').then(data => { if (!data || !data.years || !data.years.length) { hideChartLoading('pf-div-growth-chart'); return; } state.chartRawData.divGrowth = data; const ctx = $('#pf-div-growth-chart'); destroyChart('divGrowth'); const companies = data.companies; const syms = Object.keys(companies).sort(); if (!syms.length) return; const colors = ['#58a6ff','#44d17b','#e0af4f','#ff6b6b','#8ea0b8','#58a6ffcc','#44d17bcc','#e0af4fcc','#ff6b6bcc','#8ea0b8cc']; const datasets = syms.map((sym, i) => ({ label: sym + ' (DPS)', data: companies[sym].dps, backgroundColor: colors[i % colors.length] + '99', borderColor: colors[i % colors.length], borderWidth: 1, borderRadius: 2, hidden: i >= 8, })); hideChartLoading('pf-div-growth-chart'); state.charts.divGrowth = new Chart(ctx, { type: 'bar', data: { labels: data.years.map(y => String(y)), datasets, }, options: { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { y: { ticks: { color: '#8ea0b8', callback: v => formatMoney(v, 2) }, title: { display: true, text: 'DPS', color: '#8ea0b8' }, }, x: { ticks: { color: '#8ea0b8' } }, }, plugins: { legend: { position: 'right', labels: { color: '#d9e2f2', usePointStyle: true, padding: 8, font: { size: 10 } } }, tooltip: { callbacks: { label: ctx => { const sym = ctx.dataset.label.replace(' (DPS)', ''); const val = ctx.raw; if (val == null) return sym + ': N/A'; const growth = companies[sym]?.yoy_growth?.[ctx.dataIndex]; const growthStr = growth != null ? ' (YoY ' + growth.toFixed(1) + '%)' : ''; return sym + ': ' + formatMoney(val, 4) + growthStr; } } }, }, }, }); });
}

export function renderReturnsByCompanyChart() {
  showChartLoading('pf-returns-by-company-chart'); fetchJson('/api/portfolio/returns/by-company').then(data => { if (!data || !data.years || !data.years.length) { hideChartLoading('pf-returns-by-company-chart'); return; } state.chartRawData.returnsByCompany = data; _returnsByCompanyData = data; const yearSel = $('#pf-returns-year'); if (yearSel && yearSel.options.length <= 1) { yearSel.innerHTML = '<option value="all">All Years</option>'; for (const y of data.years) { const opt = document.createElement('option'); opt.value = String(y); opt.textContent = String(y); yearSel.appendChild(opt); } } _drawReturnsByCompanyChart(data); });
}

function _drawReturnsByCompanyChart(data) {
  const ctx = $('#pf-returns-by-company-chart'); destroyChart('returnsByCompany'); const decompose = $('#pf-returns-decompose')?.checked; const companies = data.companies; const yearSel = $('#pf-returns-year'); const selectedYear = yearSel?.value || 'all'; const yearIdx = selectedYear === 'all' ? -1 : data.years.indexOf(parseInt(selectedYear)); let items = []; for (const sym of Object.keys(companies)) { const c = companies[sym]; if (yearIdx >= 0) { const val = c.total_return[yearIdx]; if (val == null) continue; items.push({ sym, total: val, cap: c.capital_gain[yearIdx], div: c.dividend_return[yearIdx], }); } else { const val = c._total_all_years; if (val == null) continue; items.push({ sym, total: val, cap: val, div: 0, }); } } if (!items.length) return; items.sort((a, b) => a.total - b.total); ctx.parentNode.style.height = Math.max(350, items.length * 26) + 'px'; const labels = items.map(it => it.sym); function pnlColor(val) { if (val == null || val === 0) return '#8ea0b8'; const intensity = Math.min(Math.abs(val) / 50, 1); if (val > 0) { const g = Math.round(180 + 75 * intensity); const r = Math.round(60 - 60 * intensity); return `rgba(${r},${g},80,0.85)`; } else { const r = Math.round(180 + 75 * intensity); const g = Math.round(60 - 60 * intensity); return `rgba(${r},${g},80,0.85)`; } }
  let datasets;
  if (decompose && selectedYear !== 'all') {
    datasets = [{ label: 'Capital Gain', data: items.map(it => it.cap), backgroundColor: items.map(it => pnlColor(it.cap)), borderColor: 'transparent', borderWidth: 0, }, { label: 'Dividends', data: items.map(it => it.div), backgroundColor: items.map(it => { const v = it.div || 0; return v >= 0 ? 'rgba(68,209,123,0.4)' : 'rgba(255,107,107,0.4)'; }), borderColor: 'transparent', borderWidth: 0, }];
  } else {
    datasets = [{ label: selectedYear === 'all' ? 'Total Return (all yrs)' : 'Total Return ' + selectedYear, data: items.map(it => it.total), backgroundColor: items.map(it => pnlColor(it.total)), borderColor: items.map(it => it.total >= 0 ? '#44d17b' : '#ff6b6b'), borderWidth: 0.5, borderRadius: 2, }];
  }

  hideChartLoading('pf-returns-by-company-chart'); state.charts.returnsByCompany = new Chart(ctx, { type: 'bar', data: { labels, datasets }, options: { indexAxis: 'y', responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { x: { ticks: { color: '#8ea0b8', callback: v => v.toFixed(1) + '%' }, title: { display: true, text: 'Return %', color: '#8ea0b8' }, }, y: { ticks: { color: '#d9e2f2', font: { size: 11 } }, }, }, plugins: { legend: { display: decompose && selectedYear !== 'all', labels: { color: '#d9e2f2', usePointStyle: true }, }, tooltip: { callbacks: { label: (ctx) => { const it = items[ctx.dataIndex]; if (!it) return ''; if (decompose && ctx.dataset.label === 'Capital Gain') { return `Cap Gain: ${it.cap?.toFixed(1)}%`; } if (decompose && ctx.dataset.label === 'Dividends') { return `Dividends: ${it.div?.toFixed(1)}%`; } let s = `Total: ${it.total?.toFixed(1)}%`; if (selectedYear !== 'all' && it.div) { s += ` (Cap: ${it.cap?.toFixed(1)}%, Div: ${it.div?.toFixed(1)}%)`; } return s; }, }, }, }, }, });
}

export function renderCurrencySplitChart() {
  const hh = state.holdings.filter(h => !h.is_option && h.currency); if (!hh.length) return; const ctx = $('#pf-currency-split-chart'); destroyChart('currencySplit'); const byCcy = {}; for (const h of hh) { const ccy = h.currency || '???'; const val = Math.abs(h.market_value_native || h.market_value || 0); byCcy[ccy] = (byCcy[ccy] || 0) + val; } const labels = Object.keys(byCcy).sort(); const data = labels.map(c => byCcy[c]); const total = data.reduce((s, v) => s + v, 0); state.chartRawData.currencySplit = { labels, values: data, total }; const currencyColors = { EUR: '#44d17b', USD: '#58a6ff', JPY: '#e0af4f', GBP: '#ff6b6b', CHF: '#8ea0b8' }; const bgColors = labels.map(c => currencyColors[c] || '#8ea0b8'); hideChartLoading('pf-currency-split-chart'); state.charts.currencySplit = new Chart(ctx, { type: 'doughnut', data: { labels: labels.map(c => c + ' (' + (total > 0 ? (byCcy[c]/total*100).toFixed(1) + '%' : '0%') + ')'), datasets: [{ data, backgroundColor: bgColors, borderColor: 'transparent', }], }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'right', labels: { color: '#d9e2f2', usePointStyle: true, padding: 12 } }, tooltip: { callbacks: { label: ctx => { const ccy = labels[ctx.dataIndex]; return ccy + ': ' + formatMoney(ctx.raw); } } }, }, }, });
}

export function renderClosedReturnsChart() {
  const ccy = state.chartSettings.currency; showChartLoading('pf-closed-returns-chart'); fetchJson('/api/portfolio/holdings/closed?base_currency=' + ccy).then(closed => { state.chartRawData.closedReturns = closed || []; if (!closed || !closed.length) { const ctx = $('#pf-closed-returns-chart'); ctx.parentNode.querySelector('canvas')?.remove(); ctx.parentNode.innerHTML += '<div class="muted" style="text-align:center;padding-top:120px;">No closed positions</div>'; return; } const ctx = $('#pf-closed-returns-chart'); destroyChart('closedReturns'); closed.sort((a, b) => Math.abs(b.realized_pnl || 0) - Math.abs(a.realized_pnl || 0)); const labels = closed.map(c => c.symbol); const pnl = closed.map(c => c.realized_pnl || 0); const bgColors = pnl.map(v => v >= 0 ? 'rgba(68,209,123,0.7)' : 'rgba(255,107,107,0.7)'); const borderColors = pnl.map(v => v >= 0 ? '#44d17b' : '#ff6b6b'); hideChartLoading('pf-closed-returns-chart'); state.charts.closedReturns = new Chart(ctx, { type: 'bar', data: { labels, datasets: [{ label: 'Realized P&L', data: pnl, backgroundColor: bgColors, borderColor: borderColors, borderWidth: 1, borderRadius: 3, }], }, options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { color: '#8ea0b8', callback: v => formatMoney(v) }, title: { display: true, text: ccy, color: '#8ea0b8' }, }, x: { ticks: { color: '#d9e2f2' } }, }, plugins: { legend: { display: false }, tooltip: { callbacks: { label: ctx => 'P&L: ' + formatMoney(ctx.raw) } }, }, }, }); });
}

export function renderMoneyWeightedReturnsChart() {
  showChartLoading('pf-mw-returns-chart'); fetchJson('/api/portfolio/returns/money-weighted').then(data => { if (!data || !data.years || !data.years.length) { hideChartLoading('pf-mw-returns-chart'); return; } state.chartRawData.mwReturns = data; _mwReturnsData = data; const yearSel = $('#pf-mw-returns-year'); if (yearSel && yearSel.options.length <= 1) { yearSel.innerHTML = '<option value="all">All Years</option>'; for (const y of data.years) { const opt = document.createElement('option'); opt.value = String(y); opt.textContent = String(y); yearSel.appendChild(opt); } } _drawMWReturnsChart(data); });
}

function _drawMWReturnsChart(data) {
  const ctx = $('#pf-mw-returns-chart'); destroyChart('mwReturns'); const companies = data.companies; const yearSel = $('#pf-mw-returns-year'); const selectedYear = yearSel?.value || 'all'; const yearIdx = selectedYear === 'all' ? -1 : data.years.indexOf(parseInt(selectedYear)); let items = []; for (const sym of Object.keys(companies)) { const c = companies[sym]; if (yearIdx >= 0) { const val = c.return_pct[yearIdx]; if (val == null) continue; items.push({ sym, val }); } else { if (c._total_return != null) items.push({ sym, val: c._total_return }); } } if (!items.length) return; items.sort((a, b) => a.val - b.val); ctx.parentNode.style.height = Math.max(350, items.length * 26) + 'px'; function mwColor(val) { if (val == null || val === 0) return '#8ea0b8'; const intensity = Math.min(Math.abs(val) / 50, 1); if (val > 0) { return `rgba(${Math.round(60-60*intensity)},${Math.round(180+75*intensity)},80,0.85)`; } else { return `rgba(${Math.round(180+75*intensity)},${Math.round(60-60*intensity)},80,0.85)`; } }
  hideChartLoading('pf-mw-returns-chart'); state.charts.mwReturns = new Chart(ctx, { type: 'bar', data: { labels: items.map(it => it.sym), datasets: [{ label: 'MW Return %', data: items.map(it => it.val), backgroundColor: items.map(it => mwColor(it.val)), borderColor: items.map(it => it.val >= 0 ? '#44d17b' : '#ff6b6b'), borderWidth: 0.5, borderRadius: 2, }], }, options: { indexAxis: 'y', responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { x: { ticks: { color: '#8ea0b8', callback: v => v.toFixed(1) + '%' }, title: { display: true, text: 'Return %', color: '#8ea0b8' }, }, y: { ticks: { color: '#d9e2f2', font: { size: 11 } } }, }, plugins: { legend: { display: false }, tooltip: { callbacks: { label: ctx => 'MW Return: ' + ctx.raw?.toFixed(1) + '%' } }, }, }, });
}

export function renderContributionChart() {
  const ccy = state.chartSettings.currency; showChartLoading('pf-contrib-chart'); fetchJson('/api/portfolio/returns/contribution?base_currency=' + ccy).then(data => { if (!data || !data.years || !data.years.length) { hideChartLoading('pf-contrib-chart'); return; } state.chartRawData.contribution = data; _contribData = data; const yearSel = $('#pf-contrib-year'); if (yearSel && yearSel.options.length <= 1) { yearSel.innerHTML = '<option value="all">All Years</option>'; for (const y of data.years) { const opt = document.createElement('option'); opt.value = String(y); opt.textContent = String(y); yearSel.appendChild(opt); } } _drawContributionChart(data); });
}

function _drawContributionChart(data) {
  const ctx = $('#pf-contrib-chart'); destroyChart('contribution'); const companies = data.companies; const yearSel = $('#pf-contrib-year'); const selectedYear = yearSel?.value || 'all'; const yearIdx = selectedYear === 'all' ? -1 : data.years.indexOf(parseInt(selectedYear)); let items = []; for (const sym of Object.keys(companies)) { const c = companies[sym]; if (yearIdx >= 0) { const val = c.contribution_eur[yearIdx]; if (val == null) continue; items.push({ sym, val }); } else { let total = 0, count = 0; for (const v of c.contribution_eur) { if (v != null) { total += v; count++; } } if (count > 0) items.push({ sym, val: total }); } } if (!items.length) return; items.sort((a, b) => a.val - b.val); ctx.parentNode.style.height = Math.max(350, items.length * 26) + 'px'; hideChartLoading('pf-contrib-chart'); state.charts.contribution = new Chart(ctx, { type: 'bar', data: { labels: items.map(it => it.sym), datasets: [{ label: 'Contribution (' + (state.chartSettings.currency || '') + ')', data: items.map(it => it.val), backgroundColor: items.map(it => it.val >= 0 ? 'rgba(68,209,123,0.7)' : 'rgba(255,107,107,0.7)'), borderColor: items.map(it => it.val >= 0 ? '#44d17b' : '#ff6b6b'), borderWidth: 0.5, borderRadius: 2, }], }, options: { indexAxis: 'y', responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: 'index' }, scales: { x: { ticks: { color: '#8ea0b8', callback: v => formatMoney(v) }, title: { display: true, text: state.chartSettings.currency || '', color: '#8ea0b8' }, }, y: { ticks: { color: '#d9e2f2', font: { size: 11 } } }, }, plugins: { legend: { display: false }, tooltip: { callbacks: { label: (ctx) => { const it = items[ctx.dataIndex]; if (!it) return ''; const c = companies[it.sym]; const pct = yearIdx >= 0 ? c.contribution_pct[yearIdx] : null; let s = (state.chartSettings.currency || '') + ' ' + formatMoney(it.val); if (pct != null) s += ' (' + pct.toFixed(1) + '% of portfolio)'; return s; }, }, }, }, }, });
}

export function wireChartControls() {
  const updateBtn = $('#pf-chart-update'); const benchInput = $('#pf-chart-benchmark'); const currencySel = $('#pf-chart-currency'); const inflationCb = $('#pf-chart-inflation');
  const applySettings = () => { state.chartSettings.currency = currencySel.value; state.chartSettings.benchmark = benchInput.value.trim(); state.chartSettings.inflation = inflationCb.checked; refreshAllCharts(); };
  updateBtn.addEventListener('click', applySettings);
  $$('#pf-chart-bench-shortcuts .btn-ghost').forEach(btn => { btn.addEventListener('click', () => { benchInput.value = btn.dataset.bench; applySettings(); }); });
  currencySel.addEventListener('change', applySettings); inflationCb.addEventListener('change', applySettings);
  const breakdownCb = $('#pf-value-breakdown'); if (breakdownCb) breakdownCb.addEventListener('change', () => renderValueChart());
  const divPeriod = $('#pf-div-period'); if (divPeriod) divPeriod.addEventListener('change', () => renderDividendsChart());
  const divGrowthBtn = $('#pf-div-growth-show-dps'); if (divGrowthBtn) { divGrowthBtn.addEventListener('click', () => { _divGrowthMode = _divGrowthMode === 'per-company' ? 'agg' : 'per-company'; divGrowthBtn.textContent = _divGrowthMode === 'per-company' ? 'Aggregate' : 'Per Company'; if (_divGrowthMode === 'per-company') renderDpsPerCompanyChart(); else renderDividendGrowthChart(); }); }
  const decomposeCb = $('#pf-returns-decompose'); if (decomposeCb) decomposeCb.addEventListener('change', () => { if (_returnsByCompanyData) _drawReturnsByCompanyChart(_returnsByCompanyData); });
  const yearSel = $('#pf-returns-year'); if (yearSel) yearSel.addEventListener('change', () => { if (_returnsByCompanyData) _drawReturnsByCompanyChart(_returnsByCompanyData); });
  const mwYearSel = $('#pf-mw-returns-year'); if (mwYearSel) mwYearSel.addEventListener('change', () => { if (_mwReturnsData) _drawMWReturnsChart(_mwReturnsData); });
  const contribYearSel = $('#pf-contrib-year'); if (contribYearSel) contribYearSel.addEventListener('change', () => { if (_contribData) _drawContributionChart(_contribData); });
}

export async function refreshAllCharts() {
  const updateBtn = $('#pf-chart-update'); updateBtn.disabled = true; updateBtn.textContent = 'Applying…';
  const chartIds = ['pf-equity-chart','pf-value-chart','pf-dividends-chart','pf-allocation-chart','pf-div-growth-chart','pf-currency-split-chart','pf-returns-by-company-chart','pf-closed-returns-chart','pf-mw-returns-chart','pf-contrib-chart']; chartIds.forEach(id => showChartLoading(id));
  try { const cp = state.chartSettings; const qs = new URLSearchParams({ base_currency: cp.currency }); if (cp.benchmark) qs.set('benchmark_ticker', cp.benchmark); state.chartData = await fetchJson('/api/portfolio/performance?' + qs.toString()); } catch (e) { state.chartData = null; }
  finally { updateBtn.disabled = false; updateBtn.textContent = 'Apply Settings'; }
  renderEquityChart(); renderValueChart(); renderDividendsChart(); renderAllocationChart(); renderDividendGrowthChart(); renderReturnsByCompanyChart(); renderCurrencySplitChart(); renderClosedReturnsChart(); renderMoneyWeightedReturnsChart(); renderContributionChart();
}

export function renderEquityChart() {
  const cd = state.chartData; const cp = state.chartSettings; if (cd && cd.series) state.chartRawData.equity = cd; if (!cd || !cd.series || !cd.series.length) { fetchJson('/api/portfolio/holdings/history?base_currency=' + cp.currency).then(daily => { if (!daily.length) return; state.chartRawData.equity = { series: daily.map(d => ({ date: d.date, cumulative_return: d.cumulative_return || 0, total_value: d.total_value })) }; _drawEquityChartFromDaily(daily, cd, cp); }); return; }
  const ctx = $('#pf-equity-chart'); destroyChart('equity'); const labels = cd.series.map(pt => pt.date); const datasets = [{ label: 'Portfolio', data: cd.series.map(pt => (pt.cumulative_return || 0) * 100), borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.08)', fill: true, tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 2 }];
  if (cd.benchmark && cd.benchmark.series && cd.benchmark.series.length) { const benchMap = {}; for (const pt of cd.benchmark.series) benchMap[pt.date] = pt.cumulative_return; datasets.push({ label: cd.benchmark.ticker || 'Benchmark', data: labels.map(d => { const v = benchMap[d]; return v != null ? v * 100 : null; }), borderColor: '#e0af4f', borderDash: [2, 2], tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 1.5, spanGaps: true, }); }
  if (cp.inflation && cd.inflation_series && cd.inflation_series.length) { const infMap = {}; for (const pt of cd.inflation_series) infMap[pt.date] = pt.cumulative; datasets.push({ label: 'Inflation (' + cp.currency + ')', data: labels.map(d => { const v = infMap[d]; return v != null ? v * 100 : null; }), borderColor: '#ff6b6b', borderDash: [8, 4], tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 1, spanGaps: true, }); }
  hideChartLoading('pf-equity-chart'); state.charts.equity = new Chart(ctx, { type: 'line', data: { labels, datasets }, options: _zoomableLineOptions({ yLabel: 'Cumulative Return', yCallback: v => v.toFixed(1) + '%', }), });
}

function _drawEquityChartFromDaily(daily, cd, cp) { const ctx = $('#pf-equity-chart'); destroyChart('equity'); const datasets = [{ label: 'Portfolio', data: daily.map(d => ((d.cumulative_return || 0)) * 100), borderColor: '#58a6ff', backgroundColor: 'rgba(88,166,255,0.08)', fill: true, tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 2 }]; if (cd && cd.benchmark && cd.benchmark.series && cd.benchmark.series.length) { const benchMap = {}; for (const pt of cd.benchmark.series) benchMap[pt.date] = pt.cumulative_return; datasets.push({ label: cd.benchmark.ticker || 'Benchmark', data: daily.map(d => { const v = benchMap[d.date]; return v != null ? v * 100 : null; }), borderColor: '#e0af4f', borderDash: [2, 2], tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 1.5, spanGaps: true, }); } if (cp.inflation && cd && cd.inflation_series && cd.inflation_series.length) { const infMap = {}; for (const pt of cd.inflation_series) infMap[pt.date] = pt.cumulative; datasets.push({ label: 'Inflation (' + cp.currency + ')', data: daily.map(d => { const v = infMap[d.date]; return v != null ? v * 100 : null; }), borderColor: '#ff6b6b', borderDash: [8, 4], tension: 0.2, pointRadius: 0, yAxisID: 'y', borderWidth: 1, spanGaps: true, }); } hideChartLoading('pf-equity-chart'); state.charts.equity = new Chart(ctx, { type: 'line', data: { labels: daily.map(d => d.date), datasets }, options: _zoomableLineOptions({ yLabel: 'Cumulative Return', yCallback: v => v.toFixed(1) + '%', }), }); }

const _CHART_KEY_MAP = { 'pf-equity-chart': 'equity','pf-value-chart': 'value','pf-dividends-chart': 'dividends','pf-allocation-chart': 'allocation','pf-div-growth-chart': 'divGrowth','pf-currency-split-chart': 'currencySplit','pf-returns-by-company-chart': 'returnsByCompany','pf-closed-returns-chart': 'closedReturns','pf-mw-returns-chart': 'mwReturns','pf-contrib-chart': 'contribution', };

export function wireTableViewToggles() {
  const chartsTab = document.querySelector('[data-panel="charts"]'); if (!chartsTab) return; const panels = chartsTab.querySelectorAll('.panel'); for (const panel of panels) { const canvas = panel.querySelector('canvas'); if (!canvas) continue; const chartKey = _CHART_KEY_MAP[canvas.id]; if (!chartKey) continue; let head = panel.querySelector('.panel-head'); if (!head) { head = document.createElement('div'); head.className = 'panel-head'; panel.insertBefore(head, panel.firstChild); } if (head.querySelector('.pf-tbl-toggle')) continue; const btn = document.createElement('button'); btn.className = 'btn-ghost btn-sm pf-tbl-toggle'; btn.textContent = '📋 Table'; btn.title = 'Toggle table view'; btn.addEventListener('click', (e) => { e.stopPropagation(); _toggleTableView(panel, chartKey); }); head.appendChild(btn); }
}

function _toggleTableView(panel, chartKey) {
  const currentMode = state.chartViewMode[chartKey] || 'chart'; const canvas = panel.querySelector('canvas'); const body = panel.querySelector('.panel-body'); let tableWrap = panel.querySelector('.pf-table-wrap');
  if (currentMode === 'chart') {
    state.chartViewMode[chartKey] = 'table'; if (canvas) canvas.style.display = 'none'; panel.querySelector('.pf-tbl-toggle').textContent = '📊 Chart'; if (!tableWrap) { tableWrap = document.createElement('div'); tableWrap.className = 'pf-table-wrap'; tableWrap.style.cssText = 'overflow:auto;height:100%;'; body.appendChild(tableWrap); } tableWrap.style.display = 'block'; _renderTable(chartKey, tableWrap);
  } else {
    state.chartViewMode[chartKey] = 'chart'; if (tableWrap) tableWrap.remove(); if (canvas) { canvas.style.display = 'block'; canvas.style.width = ''; canvas.style.height = ''; } panel.querySelector('.pf-tbl-toggle').textContent = '📋 Table'; for (const k of Object.keys(state.charts)) { const ch = state.charts[k]; if (ch && ch.canvas === canvas) { requestAnimationFrame(() => ch.resize()); setTimeout(() => ch.resize(), 100); break; } }
  }
}

function _renderTable(chartKey, container) {
  const raw = state.chartRawData[chartKey]; if (!raw) { container.innerHTML = '<div class="muted" style="padding:20px;text-align:center;">No data loaded yet. Switch to chart view and ensure data is loaded.</div>'; return; }
  let columns = []; let rows = [];
  switch (chartKey) {
    case 'equity': { const cd = state.chartData; columns = ['Date', 'Portfolio %', 'Total Value']; if (cd?.benchmark?.series?.length) columns.push('Benchmark %'); if (state.chartSettings.inflation && cd?.inflation_series?.length) columns.push('Inflation %'); const benchMap = {}; if (cd?.benchmark?.series) for (const p of cd.benchmark.series) benchMap[p.date] = p.cumulative_return; const infMap = {}; if (cd?.inflation_series) for (const p of cd.inflation_series) infMap[p.date] = p.cumulative; rows = raw.series.map(pt => { const r = [pt.date, (pt.cumulative_return * 100).toFixed(2), pt.total_value?.toFixed(2)]; if (columns.includes('Benchmark %')) r.push(benchMap[pt.date] != null ? (benchMap[pt.date] * 100).toFixed(2) : ''); if (columns.includes('Inflation %')) r.push(infMap[pt.date] != null ? (infMap[pt.date] * 100).toFixed(2) : ''); return r; }); break; }
    case 'value': { columns = ['Date', 'Total Value', 'Cash', 'Stock Value', 'Option Value', 'Dividend', 'Net Inflow', 'Daily Return %', 'Cum. Return %']; rows = raw.map(d => [ d.date, d.total_value?.toFixed(2), d.cash_balance?.toFixed(2), d.stock_value?.toFixed(2), d.option_value?.toFixed(2), d.dividend_income?.toFixed(2), d.net_inflow?.toFixed(2), d.daily_return != null ? (d.daily_return * 100).toFixed(4) : '', d.cumulative_return != null ? (d.cumulative_return * 100).toFixed(2) : '', ]); break; }
    case 'dividends': { columns = ['Period', 'Gross', 'Tax', 'Net']; rows = raw.map(d => [d.period, d.gross?.toFixed(2), d.tax?.toFixed(2), d.net?.toFixed(2)]); break; }
    case 'allocation': { const total = raw.values.reduce((s, v) => s + v, 0); columns = ['Symbol', 'Market Value', '% of Portfolio']; rows = raw.labels.map((sym, i) => [sym, raw.values[i]?.toFixed(2), total > 0 ? ((raw.values[i] / total) * 100).toFixed(1) : '0.0']); break; }
    case 'divGrowth': { if (raw.companies) { columns = ['Company', 'Currency']; raw.years.forEach(y => columns.push('DPS ' + y, 'YoY ' + y)); rows = Object.entries(raw.companies).map(([sym, c]) => { const r = [sym, c.currency || '']; raw.years.forEach((y, i) => { r.push(c.dps[i] != null ? c.dps[i].toFixed(4) : '—'); r.push(c.yoy_growth[i] != null ? c.yoy_growth[i].toFixed(1) + '%' : '—'); }); return r; }); } else { columns = ['Year', 'Dividends (' + (raw.currency || 'EUR') + ')', 'YoY Growth %']; rows = raw.years.map((y, i) => [ y, raw.dividends[i]?.toFixed(2), raw.yoy_growth[i] != null ? raw.yoy_growth[i].toFixed(1) : '—', ]); } break; }
    case 'currencySplit': { columns = ['Currency', 'Native Value', '% of Total']; rows = raw.labels.map((ccy, i) => [ ccy, raw.values[i]?.toFixed(2), raw.total > 0 ? ((raw.values[i] / raw.total) * 100).toFixed(1) : '0.0', ]); break; }
    case 'returnsByCompany': { const year = $('#pf-returns-year')?.value || 'all'; columns = ['Symbol']; if (year === 'all') { columns.push('Cumulative Total %'); rows = Object.entries(raw.companies).map(([sym, c]) => [sym, c._total_all_years?.toFixed(1)]); } else { columns.push('Total Return %', 'Capital Gain %', 'Dividend Return %'); const yi = raw.years.indexOf(parseInt(year)); rows = Object.entries(raw.companies).filter(([, c]) => c.total_return[yi] != null).map(([sym, c]) => [sym, c.total_return[yi]?.toFixed(1), c.capital_gain[yi]?.toFixed(1), c.dividend_return[yi]?.toFixed(1)]); } break; }
    case 'closedReturns': { columns = ['Symbol', 'Realized P&L', 'Total Cost', 'Total Proceeds', 'Currency', 'First Trade', 'Last Trade']; rows = raw.map(c => [ c.symbol, c.realized_pnl?.toFixed(2), c.total_cost?.toFixed(2), c.total_proceeds?.toFixed(2), c.currency || '', c.first_trade_date || '', c.last_trade_date || '', ]); break; }
    case 'mwReturns': { const year = $('#pf-mw-returns-year')?.value || 'all'; if (year === 'all') { columns = ['Symbol', 'Total Return % (full period)']; rows = Object.entries(raw.companies).filter(([, c]) => c._total_return != null).map(([sym, c]) => [sym, c._total_return?.toFixed(1)]); } else { const yi = raw.years.indexOf(parseInt(year)); columns = ['Symbol', 'MW Return % (' + year + ')']; rows = Object.entries(raw.companies).filter(([, c]) => c.return_pct[yi] != null).map(([sym, c]) => [sym, c.return_pct[yi]?.toFixed(1)]); } break; }
    case 'contribution': { const year = $('#pf-contrib-year')?.value || 'all'; columns = ['Symbol']; if (year === 'all') { columns.push('Total Contribution (EUR)', 'Total Contribution %'); } else { columns.push('Contribution (' + year + ' EUR)', '% of Portfolio'); } const yi = year === 'all' ? -1 : raw.years.indexOf(parseInt(year)); rows = Object.entries(raw.companies).filter(([, c]) => { if (yi >= 0) return c.contribution_eur[yi] != null; return c.contribution_eur.some(v => v != null); }).map(([sym, c]) => { if (yi >= 0) return [sym, c.contribution_eur[yi]?.toFixed(2), c.contribution_pct[yi]?.toFixed(1)]; const tot = c.contribution_eur.reduce((s, v) => s + (v || 0), 0); const pct = c.contribution_pct.reduce((s, v) => s + (v || 0), 0); return [sym, tot.toFixed(2), pct.toFixed(1)]; }); break; }
    default: container.innerHTML = '<div class="muted" style="padding:20px;">Unknown chart type</div>'; return;
  }

  let html = '<table class="data-table" style="font-size:11px;width:100%;"><thead><tr>';
  for (const col of columns) html += `<th>${col}</th>`;
  html += '</tr></thead><tbody>';
  for (const row of rows) { html += '<tr>'; for (const cell of row) html += `<td>${cell ?? ''}</td>`; html += '</tr>'; }
  html += '</tbody></table>';
  container.innerHTML = html;
}

export function wireChartExpand() {
  const chartsTab = document.querySelector('[data-panel="charts"]'); if (!chartsTab) return; chartsTab.addEventListener('click', (e) => { const body = e.target.closest('.panel-body'); if (!body) return; const panel = body.closest('.panel'); if (!panel) return; if (e.target.closest('select, input, button, label, .btn-ghost, .btn-primary')) return; if (panel.classList.contains('chart-expanded')) panel.classList.remove('chart-expanded'); else { const other = chartsTab.querySelector('.chart-expanded'); if (other) other.classList.remove('chart-expanded'); panel.classList.add('chart-expanded'); } const resizeCanvas = () => { const canvas = panel.querySelector('canvas'); if (!canvas) return; for (const key of Object.keys(state.charts)) { const ch = state.charts[key]; if (ch && ch.canvas === canvas) { ch.resize(); break; } } }; requestAnimationFrame(resizeCanvas); setTimeout(resizeCanvas, 150); }); document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { const expanded = document.querySelector('[data-panel="charts"] .chart-expanded'); if (expanded) { expanded.classList.remove('chart-expanded'); const canvas = expanded.querySelector('canvas'); if (canvas) { for (const key of Object.keys(state.charts)) { const ch = state.charts[key]; if (ch && ch.canvas === canvas) { requestAnimationFrame(() => ch.resize()); setTimeout(() => ch.resize(), 150); break; } } } } } });
}
