"""Database locations for the application and its pipeline steps.

DB1 contains: DocumentList, financialData_full (raw ingested data).
DB2 contains: all other tables (Taxonomy, CompanyInfo, FinancialStatements,
              IncomeStatement, BalanceSheet, CashflowStatement, ShareMetrics,
              ratio tables, rolling tables, Stock_Prices).

``DATABASES`` lists every database and its default location (rebuildable
data in ``data/databases``, irreplaceable state in the state directory).
An entry in ``config/database_paths.json`` overrides a default.
"""

import json
import os
from dataclasses import dataclass

from src.paths import app_dir

_CONFIG_DIR_NAME = "config"
_CONFIG_FILE_NAME = "database_paths.json"


_PROJECT_ROOT = str(app_dir())
_CONFIG_PATH = os.path.join(_PROJECT_ROOT, _CONFIG_DIR_NAME, _CONFIG_FILE_NAME)

_cache: dict[str, str] | None = None


def _load_config() -> dict[str, str]:
    global _cache
    if _cache is not None:
        return _cache
    with open(_CONFIG_PATH, "r", encoding="utf-8") as f:
        _cache = json.load(f)
    return _cache


def _resolve(path: str) -> str:
    if os.path.isabs(path):
        return path
    return os.path.abspath(os.path.join(_PROJECT_ROOT, path))


def reload() -> None:
    """Clear the cached config so the next access re-reads from disk."""
    global _cache
    _cache = None


@dataclass(frozen=True)
class DatabaseSpec:
    """One application database.

    Rebuildable databases (raw data, standardized data, the filing catalog)
    can be regenerated by the pipeline and default to ``data/databases``. The
    others hold state that cannot be regenerated -- accounts, research notes,
    portfolio transactions, job history -- and default to ``databases/`` in
    the state directory (``EDINET_STATE_DIR``, default ``config/state``), so
    backing up the state directory covers everything irreplaceable. An entry
    in ``config/database_paths.json`` overrides either default.
    """

    key: str
    filename: str
    rebuildable: bool


DATABASES: tuple[DatabaseSpec, ...] = (
    DatabaseSpec("db1", "Base.db", rebuildable=True),
    DatabaseSpec("db2", "Standardized.db", rebuildable=True),
    DatabaseSpec("filings_db", "Filings.db", rebuildable=True),
    DatabaseSpec("bonds_db", "Bonds.db", rebuildable=True),
    DatabaseSpec("db3", "Portfolio.db", rebuildable=False),
    DatabaseSpec("auth_db", "auth.db", rebuildable=False),
    DatabaseSpec("research_db", "research.db", rebuildable=False),
    DatabaseSpec("pipeline_jobs_db", "pipeline_jobs.db", rebuildable=False),
    DatabaseSpec("chat_db", "chat.db", rebuildable=False),
)
_DATABASES_BY_KEY = {spec.key: spec for spec in DATABASES}
_REBUILDABLE_DIR = os.path.join("data", "databases")


class StateDatabaseMigrationRequired(RuntimeError):
    """A state database is still at its old location and must be moved first."""


def _state_directory() -> str:
    # Mirrors ``runtime_paths.state_dir`` but anchored at this module's
    # project root, which is the executable's folder in packaged builds.
    override = os.getenv("EDINET_STATE_DIR", "").strip()
    if override:
        return os.path.abspath(os.path.expanduser(override))
    return os.path.join(_PROJECT_ROOT, "config", "state")


def default_database_path(spec: DatabaseSpec) -> str:
    """Where a database lives when ``database_paths.json`` does not name it."""
    if spec.rebuildable:
        return _resolve(os.path.join(_REBUILDABLE_DIR, spec.filename))
    return os.path.join(_state_directory(), "databases", spec.filename)


def legacy_database_path(spec: DatabaseSpec) -> str | None:
    """Where a state database lived before state moved out of ``data/databases``."""
    return None if spec.rebuildable else _resolve(os.path.join(_REBUILDABLE_DIR, spec.filename))


def configured_database_path(key: str) -> str | None:
    """The path ``database_paths.json`` sets for a database, if any."""
    configured = _load_config().get(key)
    return _resolve(configured) if configured else None


def database_path(key: str) -> str:
    """Return the absolute path for one application database.

    Raises ``StateDatabaseMigrationRequired`` instead of returning a path at
    which an empty database would be created while the real one still sits
    at its previous location.
    """
    configured = configured_database_path(key)
    if configured:
        return configured
    spec = _DATABASES_BY_KEY[key]
    path = default_database_path(spec)
    legacy = legacy_database_path(spec)
    if legacy and not os.path.exists(path) and os.path.exists(legacy):
        raise StateDatabaseMigrationRequired(
            f"The {spec.filename} database is still at its previous location ({legacy}); "
            f"irreplaceable databases now live in {os.path.dirname(path)}. Stop the server "
            "and run `python -m src.orchestrator.common.migrate_state_databases`, or set "
            f'"{key}" in config/database_paths.json to keep using the old location.'
        )
    return path


def get_db1() -> str:
    """Return the absolute path to DB1 (raw data: DocumentList, financialData_full)."""
    return database_path("db1")


def get_db2() -> str:
    """Return the absolute path to DB2 (standardized data: all other tables)."""
    return database_path("db2")


def get_db3() -> str:
    """Return the absolute path to DB3 (portfolio module data)."""
    return database_path("db3")


def get_auth_db() -> str:
    """Return the absolute path to the non-rebuildable authentication database."""
    return database_path("auth_db")


def get_research_db() -> str:
    """Return the absolute path to the owner-scoped research-state database."""
    return database_path("research_db")


def get_pipeline_jobs_db() -> str:
    """Return the absolute path to the durable pipeline-jobs database."""
    return database_path("pipeline_jobs_db")


def get_chat_db() -> str:
    """Return the absolute path to the chat, profile, and encryption-key database."""
    return database_path("chat_db")


def get_filings_db() -> str:
    """Return the absolute path to the rebuildable filing catalog database."""
    return database_path("filings_db")


def get_bonds_db() -> str:
    """Return the absolute path to the rebuildable bond terms and yield-curve database."""
    return database_path("bonds_db")


def resolve_db_path(db_value: str | None) -> str | None:
    """Resolve a user-provided database identifier into a filesystem path.

    Behaviour:
    - If ``db_value`` is falsy, return it unchanged.
    - If ``db_value`` is an absolute path, return it unchanged.
    - If ``db_value`` contains a path separator, return its absolute path.
    - Otherwise treat ``db_value`` as a filename and attempt to locate it
      relative to the ``db2`` path. If ``db2`` points to a file, the
      filename's dirname is used; if it points to a directory that exists,
      that directory is used. Fallback: resolve relative to cwd.
    """
    if not db_value:
        return db_value
    raw = str(db_value).strip().strip("'\"")
    if os.path.isabs(raw):
        return raw
    if ("/" in raw) or ("\\" in raw):
        return os.path.abspath(raw)
    # Bare filename: try to derive a directory from db2
    try:
        db2 = get_db2()
    except Exception:
        db2 = None
    if db2:
        if os.path.isdir(db2):
            return os.path.abspath(os.path.join(db2, raw))
        base = os.path.dirname(db2) or os.getcwd()
        return os.path.abspath(os.path.join(base, raw))
    return os.path.abspath(raw)
